[root]
start_node = "say_hi"

[talk."say_hi"]
text = [
  "Oh hi, there!",
  "This is a new dialog asset.",
]
next = "random"

[talk."random"]
text = [
  {id = 0, line = "This is a random line."}
  {id = 0, line = "This another random line."}
]
